### ISSUE TITLE
Upgrade Issue with “21,000,000 CEOs” Card After Level 7

### ISSUE THREAD

**Issue by Vladyslav-webDev** [mudachyo/Hamster-Kombat#1]
Hello HamsterKombat Team,

I’ve encountered an issue within the game that I hope can be addressed. After successfully referring a friend, I unlocked the “21,000,000 CEOs” card and began upgrading it. However, upon reaching level 7, I ran into a bug. Instead of displaying the button for further upgrades, the game now shows the message “Вы владеете этой картой” (“You own this card”), and I am unable to proceed with any more upgrades. This seems to be an error since the option to continue upgrading should be available.

Could you please look into this matter and provide a fix? It is hindering my progress in the game, and I would greatly appreciate your assistance.

For reference, my Telegram account is @v3nms.

Thank you for your time and support.

![Screenshot_20240524_075554_Telegram](https://github.com/mudachyo/Hamster-Kombat/assets/42833779/468975ed-bec3-4a78-9d71-efe1ec7a2777)

**Comment by mudachyo** [comment]
There's no solution
I'm not the developer of Hamster Kombat
