### ISSUE TITLE
New game: not able to spoof as mobile screen,

### ISSUE THREAD

**Issue by lorvent** [mudachyo/Hamster-Kombat#10]
Hello,
there is a new game called Musk Empire

eventhough i tried copying code from tapswap, memefi codes from your project...
I am not able to spoof it.

when i used tapswap code and replaced div id...it is constantly reloading the page.

with memefi code, it simply detects as PC and nothing else happens.

---
when i look at code, it is passing a parameter called `platform: web` is that the culprit?

Can you please look into that project code and try to spoof as mobile?

**Comment by lorvent** [comment]
Hello,
can you please look into it?

the game is very big one and interesting one aswell.

**Comment by FoLKeR-UA** [comment]
up) realy insterested)

**Comment by REFLEXGAMING007** [comment]
Please add musk Empire 😓
