### ISSUE TITLE
hamster kombat minigames reloads page playground > minigames puzzle or hexa 

### ISSUE THREAD

**Issue by wazerstar** [mudachyo/Hamster-Kombat#14]
using https://github.com/mudachyo/Hamster-Kombat/raw/main/hamster-kombat.user.js

**Comment by wazerstar** [comment]
It can also stay in infinity loading mode..

https://streamable.com/pdx9ub

**Comment by newtoneweb** [comment]
@wazerstar you can simply open the game iframe in new tab by opening dev tools and type this in console.
`window.location.href = document.querySelector('iframe').getAttribute('src')`
@mudachyo  can you add a button to open the game in new tab?

**Comment by wazerstar** [comment]
> @wazerstar you can simply open the game iframe in new tab by opening dev tools and type this in console. `window.location.href = document.querySelector('iframe').getAttribute('src')` @mudachyo can you add a button to open the game in new tab?

Thanks I just made a bookmark link.. However its annoying it has to be like this, perhaps the coder can fix the issue without making another tab and use it without having it to be like a big tablet.

Bookmark link

`edit`

Make a bookmark from google or whatever, replace the url with this code and test.

**Comment by newtoneweb** [comment]
@mudachyo great idea.

**Comment by mudachyo** [comment]
> @wazerstar you can simply open the game iframe in new tab by opening dev tools and type this in console. `window.location.href = document.querySelector('iframe').getAttribute('src')` @mudachyo can you add a button to open the game in new tab?

Will be added in the next version
