### ISSUE TITLE
Hamster Kombat, Auto clicking issues.

### ISSUE THREAD

**Issue by wazerstar** [mudachyo/Hamster-Kombat#16]
So if keeps clicking if you are in daily cipher, which casues it to fail.

It also wants to interrupt when you are in minigames, also when clicking the "Open in a new tab"

It ruins hex game and the puzzle game.

Each time you want to try play those games you have to disable your script else it will cause issues, refreshing, crashing or games getting abandoned and you are giving an timeout.

My suggestion is to only let it auto click when you are on the front page with the anim and blue background, what do you think? Can it be done?

**Comment by mudachyo** [comment]
I'll see what I can do about it
