### ISSUE TITLE
Fix minigame position

### ISSUE THREAD

**Issue by newtoneweb** [mudachyo/Hamster-Kombat#27]
`    // Центрируем блок мини игры
    function fixMinigamePosition() {
        if (location.pathname.split("/").pop() !== "playground") return
        const minigameBg = document.querySelector('.minigame-bg');
        if (minigameBg) {
            minigameBg.style.transform = 'none';
        }
    }
    // Наблюдатель за изменениями в DOM
    const observer = new MutationObserver(function (mutations) {
        mutations.forEach(function (mutation) {
            if (mutation.addedNodes.length) {
                replaceScriptUrl();
                fixMinigamePosition()
            }
        });
    });
`

**Comment by newtoneweb** [comment]
// Центрируем блок мини игры
    function fixMinigamePosition() {
        if (location.pathname.split("/").pop() !== "playground") return
        const minigameBg = document.querySelector('.minigame-bg');
        if (minigameBg) {
            minigameBg.style.transform = 'none';
        }
    }
    // Наблюдатель за изменениями в DOM
    const observer = new MutationObserver(function (mutations) {
        mutations.forEach(function (mutation) {
            if (mutation.addedNodes.length) {
                replaceScriptUrl();
                fixMinigamePosition()
            }
        });
    });

**Comment by mudachyo** [comment]
use [Pull requests](https://github.com/mudachyo/Hamster-Kombat/pulls)

**Comment by wazerstar** [comment]
> use [Pull requests](https://github.com/mudachyo/Hamster-Kombat/pulls)

Hey have you seen the other reports I made, I think i made 3-4 of em 📦
