### ISSUE TITLE
The update was not successful!

### ISSUE THREAD

**Issue by 1r1shmann** [mudachyo/Hamster-Kombat#8]
Hello! 5 days ago you apparently wanted to update the script, but you only updated the git ignore file. The message in the commit sounds very interesting, I would like the main script to be updated.
![image](https://github.com/user-attachments/assets/8d633d12-7a68-4ac9-9441-089e4a4d9d80)

**Comment by mudachyo** [comment]
Are you kidding me? The main script was updated with gitignore.
