### ISSUE TITLE
Why Scam

### ISSUE THREAD

**Issue by Barricade** [mudachyo/Hamster-Kombat#9]
why scam with replace url?

**Comment by mudachyo** [comment]
All the code is open. If you don't understand how the game works, I'm not here to teach you how to do it.

**Comment by Barricade** [comment]
Code is open and it changes url to your service that can replace code any moment

**Comment by mudachyo** [comment]
> Code is open and it changes url to your service that can replace code any moment

Github wouldn't let me replace the file from it, so it was uploaded to my site.

If you don't trust me, don't use it. I'm not forcing you to use my scripts. Use others you trust. 🤨
